# Generated by Django 3.1.4 on 2020-12-13 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('minutos', models.CharField(max_length=50)),
                ('internet', models.CharField(max_length=50)),
                ('precio', models.CharField(max_length=50)),
            ],
        ),
    ]
